name: DeskMate UI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install root dependencies
        run: npm ci

      - name: Install UI dependencies
        run: npm --prefix packages/ui ci

      - name: Build application
        run: npm --prefix packages/ui run build

      - name: Run type checking
        run: npm --prefix packages/ui run typecheck

      - name: Run linting
        run: npm --prefix packages/ui run lint

      - name: Run smoke tests
        run: npm --prefix packages/ui run test:smoke
        env:
          BASE_URL: http://localhost:3000
