name: Deploy to Railway

on:
  workflow_dispatch:
  push:
    tags:
      - 'deskmate-ui-v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Link to Railway Project
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Deploy to Railway
        run: railway up --detach
